Formatting and lenting
OSIPI/pypi pull request #31
Opened 2024-06-04 21:41 UTC by MohamedNasser8

formatted the code using black.

There are some problems with linting as the lines should be less than 80 in length but black can't format comments which are more than 80 in length so I think all comments should be modified manually to fit in the required length.

2024-06-07 00:47 UTC, ltorres6 requested changes
Hi Mohamed,

This is a good start.
Leaving you some comments here for you to work on.

2024-06-07 00:47 UTC, ltorres6 commented on .pre-commit-config.yaml
Good start here with the linters and the formatters. 

Rather than using flake and black we should use [ruff](https://github.com/astral-sh/ruff), which would replace all of these. You can check out the documentation for how to set it up with pre-commit [here](https://docs.astral.sh/ruff/integrations/#vs-code-official). 

In addition to what you have, please configure ruff to include the isort functionality.
Lets also set the line length to 100.

2024-06-07 00:47 UTC, ltorres6 commented on .flake8
Not needed with ruff, see comment in the pre-commit file.

2024-06-07 00:47 UTC, ltorres6 commented on .github/workflows/lint.yaml
We want to replace this with a workflow that will run pre-commit. This way it will give the same results as if you were to run pre-commit locally. This way if pre-commit passes locally you can expect that this will pass as well. Additionally you only need to configure pre-commit once, rather than each of the tools here.

2024-06-07 00:47 UTC, ltorres6 commented on .github/workflows/lint.yaml
Here is one option https://pre-commit.ci/lite.html

2024-06-07 00:47 UTC, ltorres6 commented on .pre-commit-config.yaml
We also want to add pytest, but since this PR is already pretty large, what I would like for you to do is to spin off another branch (with this one as it's base) and submit a pull request from the new branch to the main branch.

2024-06-07 00:47 UTC, ltorres6 commented on .pre-commit-config.yaml
Similar to pytest, we want to include an rst file checker.

2024-06-09 11:13 UTC, MohamedNasser8 commented on .github/workflows/lint.yaml
I've implemented the Pre-commit setup as outlined, but I've retained Flake8 because it provides specific details about the lines and files that have issues—something Ruff doesn't currently offer.

2024-06-09 16:30 UTC, MohamedNasser8 commented on .pre-commit-config.yaml
I think pytest has been already implemented.
For rst-checker, it gives errors related to some directives and modules of Sphinx, so should I ignore these, **or is there a method to make rst-checker take Sphinx into account?** as I tried but didn't work.

2024-06-12 00:44 UTC, ltorres6 approved these changes
LGTM

2024-06-12 00:45 UTC, merged